In [13]:
import pandas as pd
import numpy as np

In [20]:
# Load dataset
df = pd.read_csv("../data/Metro_Manila_Traffic_Incidents_2025.csv")

In [21]:
df.drop_duplicates()

,Incident_ID,Date,Time,City,Road_Name,Vehicle_Type,Accident_Type,Severity,Weather_Condition,Road_Condition,Cause,Driver_Age,Driver_Gender,Injury_Count,Damage_Cost_PHP,Latitude,Longitude
0,MMTI-2025-0001,2025-11-24,03:01:00,Mandaluyong,Quezon Ave,Car,Rear-end,Minor,RAIN,NaN,Distracted Driving,55.0,FEMALE,0.0,5500.0,14.518739,120.946532
1,MMTI-2025-0002,2025-11-05,00:35:00,Parañaque,España Blvd,Truck,Rear-end,NaN,clear,Slippery,Overspeeding,66.0,Female,NaN,56000.0,14.568050,120.931096
2,MMTI-2025-0003,2025-06-22,03:05:00,Navotas,C5,Bus,Side-swipe,NaN,Storm,Dry,NaN,52.0,Male,3.0,12000.0,14.610408,121.065881
3,MMTI-2025-0004,2025-11-13,11:36:00,Parañaque,C5,Motorcycle,Rear-end,Fatal,Clear,Wet,Distracted Driving,42.0,male,3.0,83000.0,14.666822,120.932531
4,MMTI-2025-0005,2025-07-01,06:42:00,Mandaluyong,C5,Jeepney,Rear-end,NaN,RAIN,Wet,Drunk Driving,47.0,FEMALE,2.0,83500.0,14.637632,120.943923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,MMTI-2025-0996,2025-07-08,16:57:00,Pasay,Taft Ave,Car,Rear-end,NaN,Clear,NaN,Reckless Driving,35.0,male,4.0,51500.0,14.531973,120.940317
996,MMTI-2025-0997,2025-11-08,08:21:00,Parañaque,Ortigas Ave,Bus,Hit and Run,Minor,RAIN,Slippery,NaN,19.0,FEMALE,4.0,85000.0,14.634369,121.054003
997,MMTI-2025-0998,2025-04-15,05:07:00,Quezon City,Taft Ave,Taxi,Collision,Major,Rain,NaN,Reckless Driving,62.0,Female,4.0,40500.0,14.572188,120.910874
998,MMTI-2025-0999,2025-11-17,07:36:00,Mandaluyong,Quezon Ave,Jeepney,Collision,Fatal,Clear,Wet,Drunk Driving,39.0,Female,3.0,94000.0,14.577714,120.965472
999,MMTI-2025-1000,2025-07-20,19:48:00,Pasay,Aurora Blvd,Truck,Pedestrian,NaN,Storm,Wet,Distracted Driving,57.0,Male,0.0,5500.0,14.623855,121.071433

In [ ]:
# Removes rows where every column value is identical to another row.
df.drop_duplicates()

,Incident_ID,Date,Time,City,Road_Name,Vehicle_Type,Accident_Type,Severity,Weather_Condition,Road_Condition,Cause,Driver_Age,Driver_Gender,Injury_Count,Damage_Cost_PHP,Latitude,Longitude
0,MMTI-2025-0001,2025-11-24,03:01:00,Mandaluyong,Quezon Ave,Car,Rear-end,Minor,RAIN,NaN,Distracted Driving,55.0,FEMALE,0.0,5500.0,14.518739,120.946532
1,MMTI-2025-0002,2025-11-05,00:35:00,Parañaque,España Blvd,Truck,Rear-end,NaN,clear,Slippery,Overspeeding,66.0,Female,NaN,56000.0,14.568050,120.931096
2,MMTI-2025-0003,2025-06-22,03:05:00,Navotas,C5,Bus,Side-swipe,NaN,Storm,Dry,NaN,52.0,Male,3.0,12000.0,14.610408,121.065881
3,MMTI-2025-0004,2025-11-13,11:36:00,Parañaque,C5,Motorcycle,Rear-end,Fatal,Clear,Wet,Distracted Driving,42.0,male,3.0,83000.0,14.666822,120.932531
4,MMTI-2025-0005,2025-07-01,06:42:00,Mandaluyong,C5,Jeepney,Rear-end,NaN,RAIN,Wet,Drunk Driving,47.0,FEMALE,2.0,83500.0,14.637632,120.943923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,MMTI-2025-0996,2025-07-08,16:57:00,Pasay,Taft Ave,Car,Rear-end,NaN,Clear,NaN,Reckless Driving,35.0,male,4.0,51500.0,14.531973,120.940317
996,MMTI-2025-0997,2025-11-08,08:21:00,Parañaque,Ortigas Ave,Bus,Hit and Run,Minor,RAIN,Slippery,NaN,19.0,FEMALE,4.0,85000.0,14.634369,121.054003
997,MMTI-2025-0998,2025-04-15,05:07:00,Quezon City,Taft Ave,Taxi,Collision,Major,Rain,NaN,Reckless Driving,62.0,Female,4.0,40500.0,14.572188,120.910874
998,MMTI-2025-0999,2025-11-17,07:36:00,Mandaluyong,Quezon Ave,Jeepney,Collision,Fatal,Clear,Wet,Drunk Driving,39.0,Female,3.0,94000.0,14.577714,120.965472
999,MMTI-2025-1000,2025-07-20,19:48:00,Pasay,Aurora Blvd,Truck,Pedestrian,NaN,Storm,Wet,Distracted Driving,57.0,Male,0.0,5500.0,14.623855,121.071433

In [27]:
#Strip whitespace
df.columns = df.columns.str.strip()

for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip()

C:\Users\johnk\AppData\Local\Temp\ipykernel_23256\3396273957.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object"):

In [23]:
df.select_dtypes(include="object")

C:\Users\johnk\AppData\Local\Temp\ipykernel_23256\755674511.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object")

,Incident_ID,Date,Time,City,Road_Name,Vehicle_Type,Accident_Type,Severity,Weather_Condition,Road_Condition,Cause,Driver_Gender
0,MMTI-2025-0001,2025-11-24,03:01:00,Mandaluyong,Quezon Ave,Car,Rear-end,Minor,RAIN,NaN,Distracted Driving,FEMALE
1,MMTI-2025-0002,2025-11-05,00:35:00,Parañaque,España Blvd,Truck,Rear-end,NaN,clear,Slippery,Overspeeding,Female
2,MMTI-2025-0003,2025-06-22,03:05:00,Navotas,C5,Bus,Side-swipe,NaN,Storm,Dry,NaN,Male
3,MMTI-2025-0004,2025-11-13,11:36:00,Parañaque,C5,Motorcycle,Rear-end,Fatal,Clear,Wet,Distracted Driving,male
4,MMTI-2025-0005,2025-07-01,06:42:00,Mandaluyong,C5,Jeepney,Rear-end,NaN,RAIN,Wet,Drunk Driving,FEMALE
...,...,...,...,...,...,...,...,...,...,...,...,...
1005,MMTI-2025-0679,2025-10-23,22:51:00,Caloocan,C5,Car,Side-swipe,Minor,Rain,Dry,Traffic Violation,FEMALE
1006,MMTI-2025-0627,2025-01-12,17:25:00,Marikina,Taft Ave,UV Express,Hit and Run,Fatal,Cloudy,NaN,Distracted Driving,male
1007,MMTI-2025-0514,2025-06-02,10:37:00,Valenzuela,Aurora Blvd,Jeepney,Side-swipe,Fatal,Rain,Wet,Drunk Driving,male
1008,MMTI-2025-0860,2025-11-21,20:20:00,manila,España Blvd,Jeepney,Hit and Run,Major,Cloudy,NaN,NaN,FEMALE
1009,MMTI-2025-0137,2025-02-10,11:59:00,Valenzuela,Roxas Blvd,UV Express,Hit and Run,Major,Rain,NaN,Reckless Driving,male